### PR TITLE
Update README.md with a proper link to the demo

### PR DESCRIPTION
**Pull request by stalkermustang**
Hi, the link isn't working for some reason, but deleting `www.` solves the issue.

### CODE REVIEW

**Comment by john-b-yang** [comment]
www.swe-agent.com should work now!

**Comment by stalkermustang** [comment]
Still doesn't work for me in Malaysia 🤔

**Comment by Butanium** [comment]
This is very weird. If I click in the link in the readme it doesn't work (`ERR_CONNECTION_TIMED_OUT`) while your link here (which is the same) work. I'm in Switzerland

**Comment by stalkermustang** [comment]
It isn't the same — here in PR the link is in HTTP, not HTTP**S**

**Comment by john-b-yang** [comment]
Ok fixed! Closing this PR for now.

**Pull request closed without merging**
