### PR TITLE
Fix to issue #28 :  "Please create a docker build so that the local Conda install is not needed,"

### PR DESCRIPTION
**Pull request by jeffvun**

### CODE REVIEW

**Review by klieret — CHANGES_REQUESTED** [review]
Did you forget to add the Dockerfile to the PR?

**Comment by jeffvun** [comment]
a swe-agent.dockerfile has been added. To eliminate the need for conda local install, the configuration regarding conda and miniconda should be discarded in swe.dockerfile

**Comment by NimbleCapricorn** [comment]
Are there further changes needed to merge this PR?

**Comment by klieret** [comment]
Thank you for the PR. Unfortunately I have to close this. This wouldn't have worked because we need docker within in the container. This will be superseded by #81 .

**Pull request closed without merging**
