### PR TITLE
Black Format Codebase

### LINKED ISSUE #195: Black format codebase

### PR DESCRIPTION
**Pull request by hminsky2002**
#### Reference Issues/PRs

Fixes #195 
#### What does this implement/fix? Explain your changes.

This large commit introduces [black formatting](https://github.com/psf/black/tree/main) to the codebase, as well as adding black formatting as a pre-commit hook. Furthermore, it introduces an ignoreRev file that can be used to locally configure your git to ignore the revisions made in the extremely large reformatting commit when looking at blame logs.

Files Formatted:
All ```.py``` files
Files added:
```.git-blame-ignore-revs```
Files Modified:
```.pre-commit-config.yaml```

#### Any other comments?
This is understandably a huge PR, more just implemented as a jumping off point, there may be specific black configurations that would be more desirable. Happy to refactor/reedit, or just leave as an example!
🧡 Thanks for contributing!

### CODE REVIEW

**Comment by hminsky2002** [comment]
@klieret Here's another one, an attempt at sensibly introducing black formatting to the repository both retroactively and forwardly as a pre-commit hook. Let me know what you think!

**Comment by klieret** [comment]
Hi sorry @hminsky2002 , but I had assigned this issue to myself because I need to talk with the team again about this first. Also, such a PR will almost certainly merge conflict if not directly merged, so I'll have to close it (as it is more time to keep this updated).

**Comment by klieret** [comment]
image
you can see if someone was already assigned to an issue on the right side ;)

**Comment by hminsky2002** [comment]
@klieret No sweat! Was a neat experience working with pre-commit hooks, and I should've checked to see if there were any current assignees(duh).

**Pull request closed without merging**
