### PR TITLE
Locally hosted web UI

### PR DESCRIPTION
**Pull request by zachblume**
re: https://github.com/princeton-nlp/SWE-agent/issues/60

### CODE REVIEW

**Comment by klieret** [comment]
There's also a web-based trajectory viewer in `inspector/` that would be cool to include if we add a web interface.

More generally, though, might be worth checking Carlos/John/Ofir about whether the web UI fits into the scope of the project -- but could certainly be cool ;)

**Comment by zachblume** [comment]
Happy to keep cranking on this but would prefer others thoughts first to not go down the wrong road.

```
cd app
npm i
npm run dev
```

Should give you a basic idea of the current state of things

**Comment by klieret** [comment]
I hope to take a look later today or tmr morning!

**Comment by ofirpress** [comment]
This has been deprecated by the new web UI. Thanks

**Pull request closed without merging**
